version: '2.2'
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache

  db:
    extends:
      file: docker-services.yml
      service: db

  mq:
    extends:
      file: docker-services.yml
      service: mq

  search:
    extends:
      file: docker-services.yml
      service: search

  opensearch-dashboards:
    extends:
      file: docker-services.yml
      service: opensearch-dashboards

  pgadmin:
    extends:
      file: docker-services.yml
      service: pgadmin

  s3:
    extends:
      file: docker-services.yml
      service: s3

  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    volumes:
      - static_data:/opt/invenio/var/instance/static
      - .:/workspace
    depends_on:
      - web-ui
      - web-api
    ports:
      - "80:80"
      - "443:443"

  # UI Application
  web-ui:
    extends:
      file: docker-services.yml
      service: app
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini"]
    image: turath-inveniordm:latest
    ports:
      - "5000"
    volumes:
      - static_data:/opt/invenio/var/instance/static
      - .:/workspace

  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_rest.ini"]
    image: turath-inveniordm:latest
    ports:
      - "5000"
    volumes:
      - .:/workspace

  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    command: ["celery -A invenio_app.celery worker --beat --loglevel=INFO"]
    image: turath-inveniordm:latest
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
      db:
        condition: service_started
      mq:
        condition: service_started
    volumes:
      - .:/workspace
volumes:
  static_data:
  data: